const fs = require("fs");
const path = require("path");

// Paths are relative to the repository root (parent of scripts/)
const rootDir = path.join(__dirname, "..");
const serversDir = path.join(rootDir, "servers");
const sourceDir = path.join(rootDir, "source");
const publicDir = path.join(rootDir, "public");
const outputFile = path.join(publicDir, "server-index.js");

// Create public directory if it doesn't exist
if (!fs.existsSync(publicDir)) {
  fs.mkdirSync(publicDir, { recursive: true });
  console.log("Created public directory");
}

// Copy template files from source to public
const sourceFiles = fs.readdirSync(sourceDir);
for (const file of sourceFiles) {
  const srcPath = path.join(sourceDir, file);
  const destPath = path.join(publicDir, file);
  fs.copyFileSync(srcPath, destPath);
  console.log(`Copied ${file} to public/`);
}

// Get all game directories in servers/
const gameDirs = fs
  .readdirSync(serversDir, { withFileTypes: true })
  .filter((dirent) => dirent.isDirectory())
  .filter((dirent) => !dirent.name.includes(".WIP"))
  .map((dirent) => dirent.name);

// Read README.md from each server directory within each game directory
const games = [];
for (const gameDir of gameDirs) {
  const gamePath = path.join(serversDir, gameDir);
  const serverDirs = fs
    .readdirSync(gamePath, { withFileTypes: true })
    .filter((dirent) => dirent.isDirectory())
    .filter((dirent) => !dirent.name.includes(".WIP"))
    .map((dirent) => dirent.name);

  const servers = [];
  for (const serverDir of serverDirs) {
    const readmePath = path.join(gamePath, serverDir, "README.md");
    if (fs.existsSync(readmePath)) {
      const content = fs.readFileSync(readmePath, "utf-8");
      servers.push({
        name: serverDir,
        readme: content,
      });
      console.log(`Found README.md in: ${gameDir}/${serverDir}`);
    } else {
      console.log(`No README.md found in: ${gameDir}/${serverDir}`);
    }
  }

  if (servers.length > 0) {
    games.push({
      name: gameDir,
      servers: servers,
    });
  }
}

// Generate JS module with server data
const jsContent = `// Auto-generated server index data
// Do not edit manually - this file is generated by scripts/generate-index.js

export const serverIndex = ${JSON.stringify(
  {
    games: games,
    generatedDate: new Date().toISOString().split("T")[0],
  },
  null,
  2,
)};
`;

// Write the JS file
fs.writeFileSync(outputFile, jsContent);
const totalServers = games.reduce((sum, game) => sum + game.servers.length, 0);
console.log(`\nGenerated ${outputFile}`);
console.log(`Total games: ${games.length}`);
console.log(`Total servers indexed: ${totalServers}`);
